### ISSUE TITLE
Order's status (\"invalid\") is not acceptable for finalization

### ISSUE THREAD

**Issue by maielo** [JonahGroendal/acme-easy#12]
Hello,

First thanks for the lib :). Toying around ssl certs and it really helped. But for some reason i can't finalize the dns validation 

1. run first part as it is in example.
2. using API updates vercels dns record with supplied values.
3. waiting ~10 mins for DNS to propagate.
4. submitDnsChallengeAndFinalize & it fails

```
Error: {"type":"urn:ietf:params:acme:error:orderNotReady","detail":"Order's status (\"invalid\") is not acceptable for finalization","status":403}
```

don't know why. It fails at `postOrderFinalize`. (dns record exists, server is not yet accessible tho)

**Comment by JonahGroendal** [comment]
Hey, glad it's been helpful.

In my experience, this usually means you didn't wait long enough after setting the DNS record. 10 minutes is what I needed on Google DNS but other hosts might be different. Have you tried waiting longer? Otherwise maybe your DNS record wasn't set correctly.

If waiting longer doesn't work I'll give it a try myself to make sure the library isn't broken

**Comment by JonahGroendal** [comment]
Looks like Lets Encrypt's staging environment is currently down so that could be the issue

**Comment by JonahGroendal** [comment]
It seems to be working fine for me. I've updated the package to fix an issue with expiring replay nonces. Please update to 1.1.2 and try waiting ~30 mins after creating the DNS record

**Comment by maielo** [comment]
Thanks! 

just tested it and it works. Also my issiue was that record name per acme  _acme-<something> but it actually needs to be _acme-<something>.<domain>
